name: Sync Files to S3

on:
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2  # Change to your region if needed
        
    - name: Sync files to S3
      run: |
        aws s3 sync . s3://caringaldevops/ec2-deployments/ --exclude ".git/*" --exclude ".github/*"
        
    - name: Deployment summary
      run: |
        echo "Successfully synced files to S3 bucket"
        echo "Bucket: caringaldevops"
        echo "Path: ec2-deployments/"
        echo "Deployment time: $(date)"
