name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
        
    - name: Sync to S3 with delete flag
      run: |
        aws s3 sync . s3://caringaldevops/ec2-deployments/ --delete --exclude ".git/*" --exclude ".github/*"
        
    - name: Find EC2 instances and deploy with SSM
      run: |
        # Find all running instances with app tag
        INSTANCE_IDS=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=app-instance" "Name=instance-state-name,Values=running" \
          --query "Reservations[].Instances[].InstanceId" \
          --output text)
        
        if [ -z "$INSTANCE_IDS" ]; then
          echo "No running instances found with tag app-instance"
          exit 1
        fi
        
        echo "Deploying to instances: $INSTANCE_IDS"
        
        # Convert space-separated instance IDs to comma-separated for SSM
        COMMA_SEPARATED_INSTANCES=$(echo $INSTANCE_IDS | tr ' ' ',')
        
        # Run SSM command to update the instances
        aws ssm send-command \
          --document-name "app-deploy-index-html" \
          --targets "Key=instanceids,Values=$COMMA_SEPARATED_INSTANCES" \
          --comment "Deploy index.html from GitHub Actions $(date)"
        
        echo "Deployment command sent to all instances"